project: default
source:
  repoURL: https://github.com/sauravt01/Todo_App_Microservices.git
  path: GetTasksTodoMicroservice/manifests
  targetRevision: main
destination:
  server: https://kubernetes.default.svc
  namespace: todoapp
syncPolicy:
  automated:
    enabled: true
  syncOptions:
    - CreateNamespace=true