name: Build and Push to ACR

on:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todo-add-tasks-api
      IMAGE_TAG: v1
      ACR_NAME: devopsinsidersacr235
      ACR_LOGIN_SERVER: devopsinsidersacr235.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 345a29ed-60ef-42a4-96b5-5c0971fe4155
          tenant-id: 339559c0-6f37-4a05-baa6-05eeb41c6cd2
          subscription-id: f9fb190e-2a79-4b5f-b614-0f469a025fb0
      - name: Log in to ACR
        run: |
          az acr login --name acrtodoappsaurav007
      - name: Build Docker Image
        run: |
          docker build -t gettask GetTasksTodoMicroservice
      - name: Tag Docker Image for ACR
        run: |
          docker tag gettask acrtodoappsaurav007.azurecr.io/gettask:v1
      - name: Push Docker Image to ACR
        run: |
          docker push acrtodoappsaurav007.azurecr.io/gettask:v1
